# Generated by Django 4.2.2 on 2023-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_line_index', models.IntegerField()),
                ('middle_line_index', models.IntegerField()),
                ('right_line_index', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
